# Harbor on Longhorn in namespace `ai`
 # Domain and storage class are set for your cluster:
 # - Domain: ai.locallier.com
 # - StorageClass: longhorn

expose:
  # Using a LoadBalancer with MetalLB for LAN access
  type: loadBalancer
  loadBalancerIP: 10.10.10.81
  tls:
    enabled: false
  ingress:
    className: nginx
    hosts:
      core: ai.locallier.com
      notary: notary.ai.locallier.com
    tls:
      enabled: false

# Use in-cluster core service URL by default (internal-only)
externalURL: http://harbor.lan.locallier.com

# Admin password comes from an existing Secret created out of band
existingSecret: harbor-admin
existingSecretKey: HARBOR_ADMIN_PASSWORD

# Increase front-end Nginx limits/timeouts to allow very large image pushes
# These correspond to nginx directives client_max_body_size and proxy timeouts
nginx:
  proxyBodySize: "0"        # unlimited body size
  proxyReadTimeout: 3600     # seconds
  proxySendTimeout: 3600     # seconds

# Disable Notary; enable Trivy scanner
notary:
  enabled: false

trivy:
  enabled: true

# Ensure one pod per component by default (you can scale later if needed)
core:
  replicas: 1
registry:
  replicas: 1
portal:
  replicas: 1
jobservice:
  replicas: 1
database:
  replicas: 1
redis:
  replicas: 1

# Longhorn-backed persistence for all components
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      accessMode: ReadWriteOnce
      size: 750Gi
      storageClass: longhorn
    chartmuseum:
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: longhorn
    jobservice:
      jobLog:
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn
    database:
      accessMode: ReadWriteOnce
      size: 20Gi
      storageClass: longhorn
    redis:
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: longhorn
    trivy:
      accessMode: ReadWriteOnce
      size: 20Gi
      storageClass: longhorn

