apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-nobackup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  dataEngine: "v1"
  fsType: "ext4"
  dataLocality: "disabled"
  disableRevisionCounter: "true"
  unmapMarkSnapChainRemoved: "ignored"

